### PR TITLE
Fix `flake8` Errors and Add CI Check

### LINKED ISSUE #9: Fix Flake8 Errors in Codebase
## Problem/Opportunity Statement
Flake8 is reporting a number of style & linting errors in the code.

```
alec@laptop hubcast % flake8 hubcast/*
hubcast/__main__.py:1:1: F401 'asyncio' imported but unused
hubcast/__main__.py:2:1: F401 'importlib' imported but unused
hubcast/__main__.py:4:1: F401 'sys' imported but unused
hubcast/__main__.py:5:1: F401 'traceback' imported but unused
hubcast/__main__.py:7:1: F401 'aiohttp' imported but unused
hubcast/auth/github.py:7:1: F401 'aiohttp.web' imported but unused
hubcast/auth/github.py:104:37: W605 invalid escape sequence '\:'
hubcast/auth/github.py:104:42: W605 invalid escape sequence '\/'
hubcast/auth/github.py:105:36: W605 invalid escape sequence '\/'
hubcast/github.py:1:1: F401 'asyncio' imported but unused
hubcast/github.py:2:1: F401 'importlib' imported but unused
hubcast/github.py:10:1: F401 'gidgethub.routing' imported but unused
hubcast/github.py:43:5: F841 local variable 'exc' is assigned to but never used
hubcast/gitlab.py:1:1: F401 'asyncio' imported but unused
hubcast/gitlab.py:2:1: F401 'importlib' imported but unused
hubcast/gitlab.py:11:1: F401 'gidgetlab.routing' imported but unused
hubcast/gitlab.py:38:80: E501 line too long (82 > 79 characters)
hubcast/gitlab.py:49:5: F841 local variable 'exc' is assigned to but never used
hubcast/routes/github.py:15:80: E501 line too long (85 > 79 characters)
hubcast/routes/gitlab.py:17:80: E501 line too long (85 > 79 characters)
hubcast/routes/gitlab.py:42:24: W605 invalid escape sequence '\:'
hubcast/routes/gitlab.py:42:29: W605 invalid escape sequence '\/'
hubcast/routes/gitlab.py:43:23: W605 invalid escape sequence '\/'
```

## What would success / a fix look like?
- Address reported errors.
- Re-enable `flake8` CI tests to catch future errors before they are committed to main.

### PR DESCRIPTION
**Pull request by cook107**
Fixes #9.

### CODE REVIEW

**Comment by cook107** [comment]
What do you guys think of modifying flake8's max line length rule? It forced me to do some weird indents that I was not really a fan of the look of. When I ran black, it reverted it back to the original structure, but it breaks the flake8 rule.

**Comment by alecbcs** [comment]
Updating the max line length for flake8 sounds good to me. Can we add it in the existing `pyproject.toml` file instead of creating a separate `.flake8` config?

**Comment by cook107** [comment]
Ya I can add it to the pyproject.toml. However I need to add a new dependency in order to do that which is weird.

https://github.com/john-hen/Flake8-pyproject

**Comment by alecbcs** [comment]
Oh huh, eh let's just keep it in `.flake8`. If we really decide we need it in the `pyproject.toml` file we can add the extra dep but I'm not so sure its needed right now. 

It looks like black is failing in CI. Once that's fixed this PR looks good to me.

**Comment by cook107** [comment]
Sounds good. I fixed the pipeline so its ready to go whenever.

**Review by alecbcs — APPROVED** [review]
Looks good to me! @tgmachina did you want to weigh in here or good with you to merge?

**Pull request merged**
